#!/bin/bash

set -e

WORK_DIR=$(mktemp -d)
echo "$WORK_DIR"
cd "$WORK_DIR"

curl -o prog.zip -LJ https://github.com/Cybertron1/macsetup/archive/master.zip
unzip -q prog.zip

cd macsetup*/

# todo:
#  [x] add warning before executing anything - the user needs to know stuff will be deleted
# - [/] make it configurable to what is executed (install, config or both)
# - test install
# - test config update
# - finish README

bash ./setup