#!/bin/sh
# shellcheck disable=SC2016,SC2039
set -e

xcv() {
  sudo gem install xcode-install
  xcversion install 11 &>/dev/null  || echo "error" && return
  xcversion select 11
}

fastlane env &>/dev/null || sudo gem install fastlane
nokogiri -v &>/dev/null || sudo gem install nokogiri
xcversion -v &>/dev/null || xcv

brew install mas

brew install zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" --unattended || true

sudo chmod a+w /etc/shells
echo '/usr/local/bin/zsh' >> /etc/shells

chsh -s /usr/local/bin/zsh

rm -f ~/.zcompdump
chmod go-w '/usr/local/share'

brew cask install iterm2
brew cask install intellij-idea
brew cask install webstorm
brew cask install sourcetree
brew cask install firefox
brew cask install 1password
brew cask install alfred
brew cask install hyperswitch
brew cask install microsoft-office
brew cask install postman
brew cask install visual-studio-code
brew cask install dropbox
brew cask install spotify
brew cask install rubymine
brew cask install app-cleaner
mas install 441258766  &>/dev/null ||  echo 'Please log into the App Store'
