#!/bin/bash
set -e
sudo -v
# shellcheck source=./util.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/utils.sh"

question="\033[33mPlease make sure that this script might override some already existing files.
Do you still want to continue? (y/n):\033[0m "
answer=0
ask "$question" || answer=$?
if [ $answer -eq 1 ]; then
  echo -e "\033[33m+----------------------------------------------------------------------------------+
| ⚠️  Script was stopped. Nothing was done/changed.                                 |
+----------------------------------------------------------------------------------+\033[0m"
  exit 0
fi

[ "$MAC_SETUP_EXECUTE" != "config" ] && bash ./installs/install
[ "$MAC_SETUP_EXECUTE" != "install" ] && bash ./configures/mac

echo -e "\033[92m+----------------------------------------------------------------------------------+
| ✅ Done. Note that some of these changes require a logout/restart to take effect |
+----------------------------------------------------------------------------------+\033[0m"
