#!/bin/bash

set -e

sudo -v
for f in ./**/*; do
  sudo chmod +x "$f"
done

#cleanup
find ~ ! -name .Trash ! -name .CFUserTextEncoding ! -name .DS_Store -name '.*' -maxdepth 1 -delete

./installs/install
./configures/mac

echo -e "\033[92m+----------------------------------------------------------------------------------+
| ✅ Done. Note that some of these changes require a logout/restart to take effect |
+----------------------------------------------------------------------------------+\033[0m"
