#!/bin/bash

set -e
sudo -v

chmod 755 ~/Library/Preferences/

prefs="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/prefs"
printf "+--------------------------------------------------------------+
|  🛠  Macsetup is going to configure dev tools, apps and more  |
+--------------------------------------------------------------+\n\n"
for file in "$prefs"/*; do
  if ! [[ -d "$file" ]]; then
    name="$(basename -- "$file")"
    printf "\033[36m🛠  Next up: %s\033[0m\n" "$name"
    bash "$file"
    printf "\e[1A\e[K\033[92m🎉 finished: %s\033[0m\n\n" "$name"
  fi
done
