#!/bin/bash

set -e
sudo -v

chmod 755 ~/Library/Preferences/


prefs="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/prefs"
bash "$prefs/*"

declare -a StringArray=("Activity Monitor" "cfprefsd" "Dock" "Finder" "Mail" "Safari" "SystemUIServer" "HyperSwitch" "iTerm")
for app in "${StringArray[@]}"; do
  killall "${app}" &>/dev/null || true
done

echo "Done. Note that some of these changes require a logout/restart to take effect."
