#!/bin/bash

set -e

tools="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/tools"
[[ -e "/Library/Developer/CommandLineTools/usr/bin/git" ]] || "$tools/xcodeselect"
jabba --version &>/dev/null || "$tools/jabba"
brew --version &>/dev/null || "$tools/homebrew"
rvm -v &>/dev/null || "$tools/ruby"
nvm -v &>/dev/null || "$tools/node"

[[ $(command -v zsh) -ne "/bin/zsh" ]]  || "$tools/zsh"
"$tools/tools"
"$tools/apps"