#!/bin/bash

set -e
sudo -v
###############################################################################
# iTerm                                                                      #
###############################################################################

if ! grep -q "auth sufficient pam_tid.so" "/etc/pam.d/sudo"; then
  sudo chmod o+w /etc/pam.d/sudo
  echo -e "auth sufficient pam_tid.so\n$(cat /etc/pam.d/sudo)" >/etc/pam.d/sudo
  sudo chmod o-w /etc/pam.d/sudo
  echo "added"
fi

defaults write com.googlecode.iterm2 "AdjustWindowForFontSizeChange" -int 0
defaults write com.googlecode.iterm2 "BootstrapDaemon" -int 0
defaults write com.googlecode.iterm2 "CGFontRenderingFontSmoothingDisabled" -int 0
defaults write com.googlecode.iterm2 "DimBackgroundWindows" -int 0
defaults write com.googlecode.iterm2 "DimInactiveSplitPanes" -int 0
defaults write com.googlecode.iterm2 "DimOnlyText" -int 0
defaults write com.googlecode.iterm2 "DisableFullscreenTransparency" -int 0
defaults write com.googlecode.iterm2 "FocusFollowsMouse" -int 0
defaults write com.googlecode.iterm2 "HapticFeedbackForEsc" -int 0
defaults write com.googlecode.iterm2 "HideScrollbar" -int 0
defaults write com.googlecode.iterm2 "OnlyWhenMoreTabs" -int 0
defaults write com.googlecode.iterm2 "OpenArrangementAtStartup" -int 0
defaults write com.googlecode.iterm2 "OpenBookmark" -int 0
defaults write com.googlecode.iterm2 "OpenNoWindowsAtStartup" -int 0
defaults write com.googlecode.iterm2 "PromptOnQuit" -int 0
defaults write com.googlecode.iterm2 "SUSendProfileInfo" -int 0
defaults write com.googlecode.iterm2 "SeparateStatusBarsPerPane" -int 0
defaults write com.googlecode.iterm2 "SmartPlacement" -int 0
defaults write com.googlecode.iterm2 "SoundForEsc" -int 0
defaults write com.googlecode.iterm2 "TabViewType" -int 0
defaults write com.googlecode.iterm2 "UseBorder" -int 0
defaults write com.googlecode.iterm2 "VisualIndicatorForEsc" -int 0
defaults write com.googlecode.iterm2 "StretchTabsToFillBar" -int 0
defaults write com.googlecode.iterm2 "ShowNewOutputIndicator" -int 0

defaults write com.googlecode.iterm2 "UseLionStyleFullscreen" -int 1
defaults write com.googlecode.iterm2 "EnableDivisionView" -int 1
defaults write com.googlecode.iterm2 "EnableProxyIcon" -int 1
defaults write com.googlecode.iterm2 "FlashTabBarInFullscreen" -int 1
defaults write com.googlecode.iterm2 "HideActivityIndicator" -int 1
defaults write com.googlecode.iterm2 "HideMenuBarInFullscreen" -int 1
defaults write com.googlecode.iterm2 "HideTab" -int 1
defaults write com.googlecode.iterm2 "PreserveWindowSizeWhenTabBarVisibilityChanges" -int 1
defaults write com.googlecode.iterm2 "SUEnableAutomaticChecks" -int 1
defaults write com.googlecode.iterm2 "SeparateWindowTitlePerTab" -int 1
defaults write com.googlecode.iterm2 "ShowFullScreenTabBar" -int 1
defaults write com.googlecode.iterm2 "ShowPaneTitles" -int 1
defaults write com.googlecode.iterm2 "StatusBarPosition" -int 1
defaults write com.googlecode.iterm2 "TabStyleWithAutomaticOption" -int 5
defaults write com.googlecode.iterm2 "SplitPaneDimmingAmount" -string 0.1

plutil -insert New\ Bookmarks -xml '<dict/>' ~/Library/Preferences/com.googlecode.iterm2.plist &>/dev/null || true
for style in Regular Bold Italic 'Bold Italic'; do
    file="MesloLGS NF ${style}.ttf"
    curl -fsSL -o "$HOME/Library/Fonts/$file" "https://github.com/romkatv/powerlevel10k-media/raw/master/${file// /%20}"
done

add_or_replace() {
  sh -c "plutil -insert $1 $2 $3 $4" || sh -c "plutil -replace $1 $2 $3 $4"
}

add_or_replace "New\ Bookmarks"."Use\ Bold\ Font" -bool 1 ~/Library/Preferences/com.googlecode.iterm2.plist
add_or_replace "New\ Bookmarks"."Use\ Bright\ Font" -bool 1 ~/Library/Preferences/com.googlecode.iterm2.plist
add_or_replace "New\ Bookmarks"."Use\ Italic\ Font" -bool 1 ~/Library/Preferences/com.googlecode.iterm2.plist
add_or_replace "New\ Bookmarks"."ASCII\ Anti\ Aliased" -bool 1 ~/Library/Preferences/com.googlecode.iterm2.plist
add_or_replace "New\ Bookmarks"."Non-ASCII\ Anti\ Aliased" -bool 1 ~/Library/Preferences/com.googlecode.iterm2.plist
add_or_replace "New\ Bookmarks"."Only\ The\ Default\ BG\ Color\ Uses\ Transparency" -bool 1 ~/Library/Preferences/com.googlecode.iterm2.plist
add_or_replace "New\ Bookmarks"."Use\ Non-ASCII\ Font" -bool 0 ~/Library/Preferences/com.googlecode.iterm2.plist
add_or_replace "New\ Bookmarks"."Ambiguous\ Double\ Width" -bool 0 ~/Library/Preferences/com.googlecode.iterm2.plist
add_or_replace "New\ Bookmarks"."Prompt\ Before\ Closing\ 2" -bool 0 ~/Library/Preferences/com.googlecode.iterm2.plist

add_or_replace "New\ Bookmarks"."BM\ Growl" -integer 0 ~/Library/Preferences/com.googlecode.iterm2.plist
add_or_replace "New\ Bookmarks"."Blink\ Allowed" -integer 0 ~/Library/Preferences/com.googlecode.iterm2.plist
add_or_replace "New\ Bookmarks"."Cursor\ Type" -integer 0 ~/Library/Preferences/com.googlecode.iterm2.plist
add_or_replace "New\ Bookmarks"."Hide\ After\ Opening" -integer 0 ~/Library/Preferences/com.googlecode.iterm2.plist
add_or_replace "New\ Bookmarks"."Open\ Toolbelt" -integer 0 ~/Library/Preferences/com.googlecode.iterm2.plist
add_or_replace "New\ Bookmarks"."Scrollback\ Lines" -integer 0 ~/Library/Preferences/com.googlecode.iterm2.plist
add_or_replace "New\ Bookmarks"."Visual\ Bell" -integer 0 ~/Library/Preferences/com.googlecode.iterm2.plist
add_or_replace "New\ Bookmarks"."Blur" -integer 1 ~/Library/Preferences/com.googlecode.iterm2.plist
add_or_replace "New\ Bookmarks"."Custom\ Directory" -string "Recycle" ~/Library/Preferences/com.googlecode.iterm2.plist
add_or_replace "New\ Bookmarks"."Draw\ Powerline\ Glyphs" -integer 1 ~/Library/Preferences/com.googlecode.iterm2.plist
add_or_replace "New\ Bookmarks"."Icon" -integer 1 ~/Library/Preferences/com.googlecode.iterm2.plist
add_or_replace "New\ Bookmarks"."Reduce\ Flicker" -integer 1 ~/Library/Preferences/com.googlecode.iterm2.plist
add_or_replace "New\ Bookmarks"."Silence\ Bell" -integer 1 ~/Library/Preferences/com.googlecode.iterm2.plist
add_or_replace "New\ Bookmarks"."Show\ Status\ Bar" -integer 1 ~/Library/Preferences/com.googlecode.iterm2.plist
add_or_replace "New\ Bookmarks"."Unlimited\ Scrollback" -integer 1 ~/Library/Preferences/com.googlecode.iterm2.plist
add_or_replace "New\ Bookmarks"."Title\ Components" -integer 3 ~/Library/Preferences/com.googlecode.iterm2.plist

add_or_replace "New\ Bookmarks"."Transparency" -float 0.2892806154822334 ~/Library/Preferences/com.googlecode.iterm2.plist
add_or_replace "New\ Bookmarks"."Blur\ Radius" -float 18.47742504758883 ~/Library/Preferences/com.googlecode.iterm2.plist
add_or_replace "New\ Bookmarks"."Horizontal\ Spacing" -float 1 ~/Library/Preferences/com.googlecode.iterm2.plist
add_or_replace "New\ Bookmarks"."Vertical\ Spacing" -float 1 ~/Library/Preferences/com.googlecode.iterm2.plist
add_or_replace "New\ Bookmarks"."Minimum\ Contrast" -float 0 ~/Library/Preferences/com.googlecode.iterm2.plist

add_or_replace "New\ Bookmarks"."Normal\ Font" -string "MesloLGS-NF-Regular\ 13" ~/Library/Preferences/com.googlecode.iterm2.plist
add_or_replace "New\ Bookmarks"."Terminal\ Type" -string "xterm-256color" ~/Library/Preferences/com.googlecode.iterm2.plist

SELECTION_COLOR='<dict>
<key>Red Component</key>
<string>0</string>
<key>Color Space</key>
<string>sRGB</string>
<key>Blue Component</key>
<string>0.1623727609445383</string>
<key>Alpha Component</key>
<string>1</string>
<key>Green Component</key>
<string>0.351104736328125</string>
</dict>'

plutil -replace "New\ Bookmarks"."Selection\ Color" -xml "$SELECTION_COLOR" ~/Library/Preferences/com.googlecode.iterm2.plist

STATUS_BAR='<dict>
    <key>advanced configuration</key>
    <dict>
        <key>algorithm</key>
        <integer>1</integer>
        <key>font</key>
        <string>.AppleSystemUIFont 12</string>
    </dict>
    <key>components</key>
    <array>
        <dict>
            <key>class</key>
            <string>iTermStatusBarNetworkUtilizationComponent</string>
            <key>configuration</key>
            <dict>
                <key>knobs</key>
                <dict>
                    <key>base: compression resistance</key>
                    <integer>1</integer>
                    <key>base: priority</key>
                    <integer>5</integer>
                </dict>
                <key>layout advanced configuration dictionary value</key>
                <dict>
                    <key>algorithm</key>
                    <integer>1</integer>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>class</key>
            <string>iTermStatusBarCPUUtilizationComponent</string>
            <key>configuration</key>
            <dict>
                <key>knobs</key>
                <dict>
                    <key>base: compression resistance</key>
                    <integer>1</integer>
                    <key>base: priority</key>
                    <integer>5</integer>
                </dict>
                <key>layout advanced configuration dictionary value</key>
                <dict>
                    <key>algorithm</key>
                    <integer>1</integer>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>class</key>
            <string>iTermStatusBarGitComponent</string>
            <key>configuration</key>
            <dict>
                <key>knobs</key>
                <dict>
                    <key>base: compression resistance</key>
                    <integer>1</integer>
                    <key>base: priority</key>
                    <integer>5</integer>
                    <key>iTermStatusBarGitComponentPollingIntervalKey</key>
                    <integer>2</integer>
                    <key>maxwidth</key>
                    <string>inf</string>
                    <key>minwidth</key>
                    <integer>0</integer>
                    <key>shared text color</key>
                    <dict>
                        <key>Alpha Component</key>
                        <integer>1</integer>
                        <key>Blue Component</key>
                        <string>0.63</string>
                        <key>Color Space</key>
                        <string>sRGB</string>
                        <key>Green Component</key>
                        <string>0.63</string>
                        <key>Red Component</key>
                        <string>0.9</string>
                    </dict>
                </dict>
                <key>layout advanced configuration dictionary value</key>
                <dict>
                    <key>algorithm</key>
                    <integer>1</integer>
                    <key>font</key>
                    <string>.AppleSystemUIFont 12</string>
                </dict>
            </dict>
        </dict>
    </array>
</dict>'

plutil -replace "New\ Bookmarks"."Status\ Bar\ Layout" -xml "$STATUS_BAR" ~/Library/Preferences/com.googlecode.iterm2.plist
