#!/bin/bash

set -e

homebrew_prefix="/usr/local"

sudo mkdir -p "$homebrew_prefix"
sudo chflags norestricted "$homebrew_prefix"

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
sudo chown -R $(whoami) $homebrew_prefix/*
brew update
