#!/bin/bash
set -e

install_cask() {
  local name=$1
  brew list --cask "$name" &>/dev/null || brew install "$name" --cask || true
}

install_mas() {
  local id=$1
  mas list | grep "$id" &>/dev/null || mas install "$id" &>/dev/null
  return $?
}

apps() {
  eval "$(/opt/homebrew/bin/brew shellenv)" || true
  install_cask iterm2
  install_cask intellij-idea
  install_cask webstorm
  install_cask rubymine
  install_cask sourcetree
  install_cask 1password
  install_cask alfred
  install_cask hyperswitch
  install_cask postman
  install_cask visual-studio-code
  install_cask spotify
  install_cask typora
  install_cask whatsapp
  install_cask proxyman
  install_cask rectangle
  
  install_mas 1037126344 || printf "⚠️\033[93mPlease log into the App Store to install Apple Configurator 2\033[0m\n"

  printf "✅ \033[92mall apps installed\033[0m\n"
}

apps
