#!/bin/bash
set -e

install_plugin() {
  local plugin=$1
  local name=$2
  asdf plugin list --urls | grep $plugin &>/dev/null || asdf plugin add $name $plugin
}

install_asdf() {
  install_plugin "https://github.com/halcyon/asdf-java.git" "java"
  install_plugin "https://github.com/asdf-vm/asdf-ruby.git" "ruby"
  install_plugin "https://github.com/asdf-vm/asdf-nodejs.git" "nodejs"

  asdf install java openjdk-17.0.2
  asdf install ruby 3.1.2
  asdf install nodejs 18.10.0

  printf "✅ \033[92mall asdf tools installed\033[0m\n"
}

install_asdf
