#!/bin/bash

set -e

homebrew_prefix="/usr/local"

sudo mkdir -p "$homebrew_prefix"
sudo chflags norestricted "$homebrew_prefix"

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
sudo chown -R "$(whoami)" $homebrew_prefix/*
brew update

echo -e "✅ \e[92mhomebrew installed"