#!/bin/bash

set -e

install() {
  if command -v brew >/dev/null; then
    printf "⚠️  \033[93mhomebrew already installed\n"
    # shellcheck source=../../util.sh
    source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../../utils.sh"
    question="Do you want to reinstall homebrew?\033[0m (y/n): "
    exit_code=0
    ask "$question" || exit_code=$?
    if [ $exit_code -eq 1 ]; then
      return
    fi
    # uninstall homebrew
    printf "Removing cask install"
    brew cask uninstall --force "$(brew list --cask)" &>/dev/null || true
    printf "Removing brew install"
    brew remove --force "$(brew list)"
    SH="$(mktemp -d)/uninstall.sh"
    curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh --output "$SH"
    sudo /bin/bash "$SH" -f -q || true
  fi
  homebrew_prefix="/usr/local"

  sudo mkdir -p "$homebrew_prefix"
  sudo chflags norestricted "$homebrew_prefix" >/dev/null
  export CI="install"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  sudo chown -R "$(whoami)" $homebrew_prefix/*
  brew update >/dev/null

  printf "✅ \033[92mhomebrew installed\033[0m\n"
}

install
