#!/bin/bash

set -e

install() {
  if [[ -d "$HOME/.jabba" ]]; then
    printf "⚠️  \033[93mJabba already installed\033[0m\n"
    return
  fi
  curl -sL https://github.com/shyiko/jabba/raw/master/install.sh | bash -s -- --skip-rc && . ~/.jabba/jabba.sh >/dev/null

  printf "✅ \033[92mJabba installed\033[0m\n"
}
install
