#!/bin/bash

set -e

curl -sL https://github.com/shyiko/jabba/raw/master/install.sh | bash && . ~/.jabba/jabba.sh >/dev/null

printf "✅\033[92mJabba installed - no Java version was installed\033[0m\n"