#!/bin/bash

set -e

# Install nvm
curl -o- https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" 

# Install and use node version 10 by default
nvm install 12
nvm alias default 12

printf "✅\033[92mnvm and node 12 installed\n"