#!/bin/bash

set -e

# Install nvm
curl -o- https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash >/dev/null

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" >/dev/null
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" >/dev/null

# Install and use node version 10 by default
nvm install 12 >/dev/null
nvm alias default 12 >/dev/null

printf "✅\033[92mnvm and node 12 installed\033[0m\n"