#!/bin/bash

set -e



\curl -sSL https://get.rvm.io | bash -s stable
export PATH="$PATH:$HOME/.rvm/bin"
source ~/.rvm/scripts/rvm
rvm install ruby --latest

echo -e "✅ \e[92mrvm and latest ruby installed"