#!/bin/bash
set -e

xcv() {
  sudo gem install xcode-install
  xcversion update
  xcversion install 11.6 >/dev/null  || printf "✅ \033[91mcouldn't install xcode 11\033[0m\n" && return
  xcversion select 11.6
}

xcversion -v &>/dev/null || xcv
fastlane env &>/dev/null || sudo gem install fastlane  >/dev/null
nokogiri -v &>/dev/null || sudo gem install nokogiri  >/dev/null

brew list mas &>/dev/null || brew install mas  >/dev/null
