#!/bin/bash
set -e

xcv() {
  sudo gem install xcode-install
  xcversion install 11 &>/dev/null  || printf "✅ \033[91mcouldn't install xcode 11\n" && return
  xcversion select 11
}

xcversion -v &>/dev/null || xcv
fastlane env &>/dev/null || sudo gem install fastlane
nokogiri -v &>/dev/null || sudo gem install nokogiri

brew list mas &>/dev/null || brew install mas
