#!/bin/bash

set -e
sudo -v
OS_VERSION=$(sw_vers -productVersion | cut -d'.' -f 1-2)

touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress;
PROD=$(softwareupdate -l |
  grep "\*.*Command Line *.* version $OS_VERSION" |
  head -n 1 | awk -F"*" '{print $2}' |
  sed -e 's/^ *//' |
  tr -d '\n')
softwareupdate -i "$PROD" --verbose
rm /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
/usr/bin/xcode-select --switch /Library/Developer/CommandLineTools
printf "✅\033[92mCommandLineTools were installed\033[0m\n"
