#!/bin/bash

set -e
sudo -v

getc() {
  local save_state
  save_state=$(/bin/stty -g)
  /bin/stty raw -echo
  IFS= read -r -n 1 -d '' "$@"
  /bin/stty "$save_state"
}

sudo /usr/bin/xcode-select --install
echo "Press any key when the installation has completed."
getc
sudo /usr/bin/xcode-select --switch /Library/Developer/CommandLineTools
printf "✅\033[92mCommandLineTools were installed\033[0m\n"
