#!/bin/bash
set -e

install() {
  #install zsh
  eval "$(/opt/homebrew/bin/brew shellenv)" || true
  if [[ -d "$HOME/.oh-my-zsh" ]] || brew list zsh &>/dev/null ; then
    printf "⚠️ \033[93m zsh is already installed\033[0m\n"
    # shellcheck source=../../util.sh
    source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../../utils.sh"
    question="Do you want to reinstall zsh, oh-my-zsh and powerlevel10k?
This will remove .zshrc, .bashrc, .bash_profile, .bash_history\033[0m (y/n): "
    exit_code=0
    ask "$question" || exit_code=$?
    if [ $exit_code -eq 1 ]; then
      return
    fi
    brew uninstall zsh &>/dev/null || true
    rm -rf ~/.oh-my-zsh
  fi
  brew install zsh
  rm -rf "$HOME/.zshrc"
  rm -rf "$HOME/.bashrc"
  rm -rf "$HOME/.bash_profile"
  rm -rf "$HOME/.bash_history"
  if ! [[ -d "$HOME/.oh-my-zsh" ]]; then
    RUNZSH=no sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" --unattended || true
  fi

  if ! grep -q "/opt/homebrew/bin/zsh" /etc/shells; then
    sudo chmod a+w /etc/shells
    echo '/opt/homebrew/bin/zsh' >>/etc/shells
    chsh -s /opt/homebrew/bin/zsh
  fi
  rm -f ~/.zcompdump
  sudo chmod go-w '/opt/homebrew/share'

  #install theme & plugins
  dir=~/.zsh
  rm -rf $dir
  mkdir -p $dir
  p10k="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k"

  if ! [[ -d "$p10k" ]]; then
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "$p10k"
  fi

  chmod 755 /opt/homebrew/share/zsh
  chmod 755 /opt/homebrew/share/zsh/site-functions
}

install
