#!/bin/bash

sudo -v
SH="$(mktemp -d)/uninstall.sh"


pwd
sudo rm -rf /Library/Developer/CommandLineTools
if hash rvm 2>/dev/null; then
  sudo rvm implode
fi

chsh -s /bin/zsh

find ~ ! -name .Trash ! -name .CFUserTextEncoding ! -name .DS_Store -name '.*' -maxdepth 1 -exec rm -rf {} \;

defaults delete com.bahoom.HyperSwitch
defaults delete com.googlecode.iterm2
defaults delete com.crowdcafe.windowmagnet
defaults delete com.apple.dock


if command -v brew; then
  brew cask uninstall --force $(brew cask list) &>/dev/null || echo "cask remove didn't work"
  curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh --output "$SH"
  ls
  sudo /bin/bash "$SH" -f -q || true
fi

