#!/bin/bash

set -e

sudo -v

sudo rm -rf /Library/Developer/CommandLineTools
if hash rvm 2>/dev/null; then
  sudo rvm implode
fi

chsh -s /bin/zsh

find ~ ! -name .Trash ! -name .CFUserTextEncoding ! -name .DS_Store -name '.*' -maxdepth 1 -exec rm -rf {} \;
which -s brew
if [[ $? == 0 ]]; then
  brew cask uninstall --force $(brew cask list) &>/dev/null || echo "cask remove didn't work"
  sudo /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh) -f -q" || true
fi

